version: '3.4'

services:

  app:
    build: .
    command: run-app
    volumes:
      - './:/app'
    depends_on:
      - rabbitmq
    ports:
      - 5000:5000

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
